### ISSUE TITLE
On visual studio 2013 this fails to compile

### ISSUE THREAD

**Issue by janwilmans** [copperspice/libguarded#4]
```cpp
#include "libguarded/guarded.hpp"

struct Foo
{
    int value;
};

int main()
{
    libguarded::guarded<Foo> m_foo;
    auto lock = m_foo.lock();
    return 0;
}
```

```
1>c:\program files (x86)\microsoft visual studio 12.0\vc\include\memory(1377): error C2280: 'std::unique_lock<M>::unique_lock(const std::unique_lock<M> &)' : attempting to reference a deleted function
1>          with
1>          [
1>              M=std::mutex
1>          ]
1>          c:\program files (x86)\microsoft visual studio 12.0\vc\include\mutex(285) : see declaration of 'std::unique_lock<M>::unique_lock'
1>          with
1>          [
1>              M=std::mutex
1>          ]
1>          This diagnostic occurred in the compiler generated function 'libguarded::guarded<Foo,std::mutex>::deleter::deleter(const libguarded::guarded<Foo,std::mutex>::deleter &)'
```

**Comment by janwilmans** [comment]
confirmed ansel's suspicion, its vs2013 specific, in vs2017 just works

**Comment by janwilmans** [comment]
It does however also not compile on gcc 4.6.4 or earlier, see https://godbolt.org/g/vkvEZ4

**Comment by agserm** [comment]
As noted in the readme, libguarded does require a standard compliant c++11 compiler. I think you have found yet another place in which vs2013 just isn't capable of handling c++11 code. I have no idea why, but I agree that it looks like the move constructor for std::unique_ptr calls the copy constructor for the deleter. That's just incorrect. The only requirement the standard puts on the deleter here is that it be NothrowMoveConstructible, which it definitely is.

I'm not sure what is failing on gcc 4.6.4, but I would not expect that to work since c++11 support was still in pretty rough shape at that point as well.

**Comment by Nik-Lz** [comment]
It could be `/Zc:rvalueCast-` flag that is causing the trouble. MSVS starting from C++11, treats as rvalue categories all expressions that result in rvalue reference types.
Check [here](https://docs.microsoft.com/en-us/cpp/build/reference/zc-rvaluecast-enforce-type-conversion-rules?view=vs-2017). Starting from MSVS2017 Microsoft has started paying more attention to the standard and now by default enables `/permissive-` (which is an aggregate flag for `Zc:rvalueCast` and others). So try setting `/permissive-` to pre-MSVS2017, note though that it could break existing code.

**Comment by janwilmans** [comment]
I would like to offer a merge request to support libguarded also on vs2013 + boost (boost because it has shared_mutex and a working chrono, which vs2013 has not), I think this can be done with very limited change, but would add some 'toggle macro' logic to conditionally define some things like:

```
#ifndef HAVE_CXX14
	#include <boost/thread/shared_mutex.hpp>
	using shared_mutex = boost::shared_timed_mutex;
	namespace chrono = boost::chrono;
#else
	#include <shared_mutex>
	using shared_mutex = std::shared_timed_mutex;
	namespace chrono = std::chrono;
#endif
```

**Comment by agserm** [comment]
I have no issue with adding defines for HAVE_CXX14, and in fact I thought that already was in place. For example, I just looked at shared_guarded and it has:

```
#if HAVE_CXX14
#include <shared_mutex>
#else
namespace std
{
class shared_timed_mutex;
}
#endif
```

This means that in your code, you will need to use `shared_guarded<MyType, some_specific_mutex_class>` if you are in a pre-C++14 compiler, but that seems reasonable since there is no standard mutex class which meets the requirements in C++11. I am not so enthusiastic about having a class like shared_guarded do a `#include <boost/whatever...>` if you are in C++11. Libguarded uses boost in the unit test suite only. By design the implementation is completely thread library agnostic and I would like to keep it that way.

I am very curious to know if there are classes in libguarded that do not work in a C++11 + boost environment, and I definitely think libguarded should support that use case. Let me know what changes are needed and we will figure out a way to make it happen.

 Thanks to everyone for the hard work and feedback!

**Comment by janwilmans** [comment]
I did not understand the way the forward declaration was suppose to be used.

would this work?
```
namespace std
{
   using shared_timed_mutex = boost::shared_timed_mutex;
}
#include "shared_guarded.hpp"
```

The enable_if's in ordered_guarded causes me much pain / compiler crashes in vs2013.

I like your approach to keep boost out of libguarded header, I just did not see a way to do that yet.

**Comment by agserm** [comment]
Putting a using of your own in namespace std is not a good idea. (Truthfully, putting a forward declaration in namespace std as the code currently does is not a good idea either, and that needs to be changed to remove the default value for the mutex template parameter instead.) What I envisioned is something like this:

```
namespace my_app {
template<typename T>
using my_shared_guarded = libguarded::shared_guarded<T, boost::shared_timed_mutex>;
}
```
Then, you can simply use my_shared_guarded<T> in place of libguarded::shared_guarded<T> and you are set.

Does that address the use case or is there something that could be done to improve this?

**Comment by janwilmans** [comment]
That is exactly what i did here except i default  to boost. We could very well default to a forward declaration that is not in std like you did.

 https://github.com/janwilmans/libguarded/blob/master/src/libguarded/feature_check.hpp

However, I would like to do that is one place so can still 'just' include your normal headers. So when switching to c++14, user code does not change

**Comment by agserm** [comment]
I understand your desire to have some test to automatically switch from using boost::shared_timed_mutex to std::shared_timed_mutex based on a compile time check. This could be a serious ABI compatibility issue though. This would change the mangled name of libguarded::shared_guarded<T> by simply changing the version of the standard your compiler is using, which would make code using C++11 not linkable with C++14 in the same project. This could also affect multiple libraries, if you use libguarded types in a library api.

This is a perfectly reasonable thing to do in your project, but it does not seem like something we should do silently in libguarded. Do you have an idea how we could make the user experience better without giving people the opportunity to cause ABI linkage problems?

**Comment by agserm** [comment]
Closing this ticket since the original issue was supporting non standard compliant compilers.
